# Generated by Django 4.2.6 on 2023-10-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_category_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
