# Generated by Django 4.2.6 on 2023-10-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
