# Generated by Django 4.1.3 on 2023-10-27 16:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='AddedBooks',
        ),
        migrations.RenameField(
            model_name='addedbooks',
            old_name='user',
            new_name='user_id',
        ),
    ]
