# Generated by Django 4.1.3 on 2023-11-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_userlikedbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLikedBook',
        ),
    ]
