# Generated by Django 4.1.3 on 2023-10-26 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_alter_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_books', models.ManyToManyField(blank=True, related_name='liked_by', to='books.book')),
                ('read_books', models.ManyToManyField(blank=True, related_name='read_by', to='books.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wish_books', models.ManyToManyField(blank=True, related_name='wished_by', to='books.book')),
            ],
        ),
    ]
